name: Tests

on:
  # unsafe presubmit
  pull_request_target:
    branches:
      - main
      - '[0-9]+.x'
      # For testing purposes so we can stage this on the `gha` branch.
      - gha
    types: [labeled]

jobs:
  trigger:
    name: Trigger
    if: github.event.label.name == 'safe for tests'
    uses: ./.github/workflows/test_runner.yml
    with:
      checkout: ${{ github.event.pull_request.head.sha }}
    secrets: inherit
